spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookdb?serverTimezone=UTC&cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true
    username: root
    password: root
  jpa:
   # show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
#        cache:
#          use_second_level_cache: true
#        order_updates: true
#        order_inserts: true
#        generate_statistics: true